version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret_password

  redis:
    image: redis

  server:
    image: sacmi5/tempservice
    environment:
      FCM_SERVER_KEY: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  db-data:
