spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/temperature
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080