
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host:
    port:

firebase:
  cloud-messaging:
    server-key:
