
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: redis
    port: 6379

firebase:
  cloud-messaging:
    server-key: ${FCM_SERVER_KEY}
